### ISSUE TITLE
Unable to add activity to day before current day

### ISSUE THREAD

**Issue by pokorj54** [projecthamster/hamster#682] opened 2021-05-30 07:24 UTC
When I add activity to yesterday, the activity places itself to day before yesterday and replaces any activity in that time. If I want to edit it to yesterday's date, it still ends up in the day before activity list.

**Comment by szebenyib** [comment] 2021-06-01 04:36
Same here. You can avoid it only by later on modifying the date in the cmdline. So choosing via the calendar does not work.

**Comment by szebenyib** [comment] 2021-06-01 04:38
This seems to be known in: [627](https://github.com/projecthamster/hamster/issues/627) and [590](https://github.com/projecthamster/hamster/issues/590`)

**Comment by GeraldJansen** [comment] 2021-06-01 14:11
Probably fixed by #674.

**Comment by DirkHoffmann** [comment] 2023-11-19 22:18
I cannot reproduce the problem (but had seen something similar in the past) in [3.0.3](https://github.com/projecthamster/hamster/releases/tag/v3.0.3). 
Hence closing until further notice.

PS: Entering activities (in the past or in general) during "night time" (as defined in the user configuration) is tricky, because a time like 02:00 (AM) will be counted (and displayed) on the previous day. Check your configuration and (system) timezone setup in that case to adapt them to your needs.

**Closed by DirkHoffmann** 2023-11-19 22:18 UTC
