### ISSUE TITLE
Overlap of time period and project name

### ISSUE THREAD

**Issue by petrovo-as** [projecthamster/hamster#716] opened 2023-03-27 10:02 UTC
[![2023-03-27-11-27-58.png](https://i.postimg.cc/BbZyJG7Y/2023-03-27-11-27-58.png)](https://postimg.cc/bDMLR4hk)

I changed the GTK font and in the overview of daily activities the time period of activities overlaps with the name of the project. It looks like a fixed width is set for the times.
I'd be happy to donate coffee or beer to the developers for this fix.

**Comment by GeraldJansen** [comment] 2023-03-27 11:09
Duplicate of #698 fixed in #699.

**Comment by petrovo-as** [comment] 2023-03-27 11:15
Thanks. Sorry, I haven't read all the issues.

**Closed** 2023-03-27 11:15 UTC
