### ISSUE TITLE
Misalignment of drop down menus

### ISSUE THREAD

**Issue by InRiPa** [projecthamster/hamster#734] opened 2023-10-11 10:50 UTC
Hi,
I got a multi-monitor setup (3 screens with different resolutions) and a problem, hopefully someone can help me with.
My issue is, that the drop down menus are only correctly aligned at one monitor. For the other ones, the menu appears quite far away, rendering impossible to use on smaller screens. I attached to images which should describe the issue way more clear than in text form. 

Here, everything is fine (smaller resolution monitor):
![just_fine](https://github.com/projecthamster/hamster/assets/4258969/779ed12d-b92b-429f-b43b-3e3b79b55e74)

Here, the pop up menu is far to the right (higher resolution monitor). 

![too_far](https://github.com/projecthamster/hamster/assets/4258969/10d332ba-38a0-42da-a0e5-3e4288c2d1ed)

On my third monitor. I can't even see the menu anymore (probably doesn't fit on to the screen). 

## Setup

Arch Linux
GNOME Shell 45.0
hamster-time-tracker 3.0.2-5

**Comment by GeraldJansen** [comment] 2023-10-11 18:51
Duplicate of #658?

**Comment by InRiPa** [comment] 2023-10-23 07:55
Yea, seems to be the same issue. So this one can be probably closed.

**Closed** 2023-10-24 07:52 UTC
