### ISSUE TITLE
"Add earlier activity" dialog no longer shows up from Shell extension

### ISSUE THREAD

**Issue by Forage** [projecthamster/hamster#548] opened 2020-02-11 13:37 UTC
With the 3.0-beta, clicking on the "Add earlier activity" menu entry from the GNOME Shell extension no longer makes the dialog pop up. Other entries like the overview and settings work as expected.

An intermediate build on 30 October worked as expected.
Calling the same dialog from the overview dialog works as well.

Is there any way I can have a Shell extension provide me with log messages?
Could this be another case of some outdated/duplicate files lingering somewhere due to file/folder name changes?

**Comment by ederag** [comment] 2020-02-11 14:27
Thank you for the report, it's good to have early testing, especially for the shell-extension !
(still none here...)

> Is there any way I can have a Shell extension provide me with log messages?

No idea.

> clicking on the "Add earlier activity"

OK, thanks for that.
Following the track leads to
[this](https://github.com/projecthamster/hamster-shell-extension/blob/11f4dfaf7bed351793912fad6ca99dafed5d6de9/extension/widgets/panelWidget.js#L118-L119) and [this](https://github.com/projecthamster/hamster-shell-extension/blob/11f4dfaf7bed351793912fad6ca99dafed5d6de9/extension/widgets/panelWidget.js#L312-L313)
ending with `editSync` which is not explicitly defined.

It was my mistake to remove the `edit` method in #538.

**Comment by ederag** [comment] 2020-02-11 14:58
@Forage #549 should allow you to continue using the extension,
(dbus interface tested with d-feet only)
but the real "edit" (of a specific fact) will be less simple.
I'll get back to that this evening or tomorrow.

**Comment by mwilck** [comment] 2020-02-11 20:25
The extension tries to open the "edit" method of `org.gnome.Hamster.WindowServer` and fails:

    method call time=1581452687.413741 sender=:1.252 -> destination=:1.259 serial=495 path=/org/gnome/Hamster/WindowServer; interface=org.gnome.Hamster.WindowServer; member=edit
        variant       int32 0
    error time=1581452687.414817 sender=:1.259 -> destination=:1.252  error_name=org.freedesktop.DBus.Error.UnknownMethod reply_serial=495
    string "Traceback (most recent call last):
    File "/usr/lib/python3.7/site-packages/dbus/service.py", line 658, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
    File "/usr/lib/python3.7/site-packages/dbus/service.py", line 248, in _method_lookup
      raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
      dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: edit is not a valid method of interface org.gnome.Hamster.WindowServer

**Comment by mwilck** [comment] 2020-02-11 20:38
I guess it's caused by commit 0cffe9c2c7e669a3b0557a15f61e2a8ea538be21.

**Comment by mwilck** [comment] 2020-02-11 20:39
Argh, I should have read more carefully. You tracked that down already... Sorry.

**Comment by GeraldJansen** [comment] 2020-02-14 06:46
I can confirm that (temporarily) reverting 0cffe9c gets the edit buttons and Add Earlier Activity menu item working also in xfce-hamster-plugin. Nearly everything seems to be working with the plugin, so Yay!

**Comment by ederag** [comment] 2020-02-15 23:07
Fixed now in #549.

**Closed** 2020-02-18 08:31 UTC
