### ISSUE TITLE
Inserting an activity name starting with a decimal number causes activity name to be overwritten

### ISSUE THREAD

**Issue by clapham** [projecthamster/hamster#270] opened 2015-12-07 14:14 UTC
Fails on both 1.04 and master branch

Steps to reproduce:
1. Click Add Earlier Activity
2. Enter "10.0@ABC" in the activity field
3. Enter "Hello World" in the description field (any text will do but must be longer then one word)
4. Click Save

Expected result
1. The activity and the description should be saved correctly

Actual result:
1. The activity field has the second and subsequent words from the description field entered in step 3 above
2. The description is blank

**Comment by ederag** [comment] 2019-02-03 20:39
Thanks for the detailed report, with steps to reproduce !

This is fixed in current master (tested with 79db77f70f9d1701cc17b53e3b8dbe2e823e7b81).
![screenshot_20190203_213751](https://user-images.githubusercontent.com/10962809/52182291-f60f8e80-27fb-11e9-9df7-df300f54d9a7.png)

Leaving open with the hamster-applet label (for the 1.04 version)

**Comment by pwhipp** [comment] 2019-07-09 20:40
Probably related so noting this here: in my imported hamster.db I have lots of activities that start with an issue number prefixed by #. These are all coming up blank in the display and when exported.

I was able to workaround the issue by replacing the # with a text string in the db.

**Comment by ederag** [comment] 2019-07-10 12:04
@pwhipp Thanks for the report, but could you please open a new issue,
because this one has the "hamster-applet" tag
(meaning fixed in current versions).
And the issue you describe is actually quite different (related to `#` character and affecting the import too).

**Comment by ederag** [comment] 2019-08-14 14:36
Closing, since the main issue is thought to be solved in the development version.
Thanks for contributing to hamster improvement !

**Closed by ederag** 2019-08-14 14:36 UTC
Labels: bug, hamster-applet, use_case
