### ISSUE TITLE
Calendar date picker date mismatch

### ISSUE THREAD

**Issue by kidorion** [projecthamster/hamster#667] opened 2021-01-16 04:37 UTC
The date picked in graphical UI calendar doesn't match the date applied to command line.
My guess is a locale problem. My locale is Sydney, Australia = UTC+10 or UTC+11 during summer.
I'm using Linux Mint Debian 10.2 buster, Cinnamon desktop 4.6.7.
Goal: try and make an entry for yesterday Friday 2021-01-15 09:00-15:00
Thanks..
Steps to reproduce are:
1. Add activity
1. Enter start time as 09:00
1. Select started date in calendar graphical UI as 2021-01-15
1. Date in command line is 2021-01-14
See image:
![image](https://user-images.githubusercontent.com/53280834/104797038-5cd2ba80-580f-11eb-924b-d90941472377.png)

Also browsing past entries using the Graphical UI show similar out-by-one-day errors.

**Comment by GeraldJansen** [comment] 2021-01-16 07:04
Hamster just works with local times so I don't believe your location is the issue. More likely this is a duplicate of previously reported issues being worked on in #630. (Hopefully work on this very important issue will be resumed soon!)

**Comment by ederag** [comment] 2021-01-16 08:37
There has been a fix pending for 8 months and a half: https://github.com/projecthamster/hamster/pull/597#issuecomment-622463737

**Comment by Pops34** [comment] 2021-02-17 06:00
same problem
It's the 17th, I want to add an activity from the previous day, the 16th, I go back to Tuesday the 16th, the software displays Monday the 15th (inconsistent date), and when I want to correct the date by adding an activity, there is a difference between the selected date and the saved command line.  
![bug1](https://user-images.githubusercontent.com/62051042/108162200-e87c8700-70ec-11eb-9c54-f788e065baa7.png)
![bug2](https://user-images.githubusercontent.com/62051042/108162202-e9151d80-70ec-11eb-821b-95a87306ab5f.png)

**Comment by ederag** [comment] 2021-02-17 07:07
A fix has been pending for 9 months and a half: https://github.com/projecthamster/hamster/pull/597#issuecomment-622463737

**Comment by GeraldJansen** [comment] 2021-02-17 08:31
@ederag That fix has been rejected by current maintainers and closed for several months now. If you are still interested in making a positive contribution to the project please consider making a new minimal pull request based on current master. Otherwise please do us all a favour and move on.

**Comment by ederag** [comment] 2021-02-17 10:33
> do us all a favour and move on

Interesting tone.
Where is your aspiration to democracy (I just give information to this community) ? 
Or was it just about power ?
Do you realize that the current maintainers, by letting this issue rot, and letting duplicates pile up, 
give a wrong impression of our quality ?
People notice only the interface, which was on its way to become as robust as the infrastructure.
But I gave up on that, since the new team clearly has different views.

> If you are still interested in making a positive contribution to the project please consider making a new minimal pull request based on current master.

Why would I take that time ? The previous one was discarded because they *play the boss*.
The fix is available for anyone to test, it's easy.

> That fix has been rejected by current maintainers and closed for several months now.

They overlooked some aspects, as explained in https://github.com/projecthamster/hamster/pull/630#issuecomment-731761920,
and at least one clearly understood the rationale: https://github.com/projecthamster/hamster/pull/630#issuecomment-732830377.

**Comment by matthijskooijman** [comment] 2021-02-17 12:11
I do not think discussion on the merits of your PR should happen here, so I added a comment there to further clarify why I closed it, to prevent further clouding discussion here.

However, I do believe that @GeraldJansen makes a good point. @ederag, if you're interested in adding information to duplicate issues, I suggest you link to a relevant existing open issue or pullrequest, rather than your own comment on your own PR. Right now, it sounds to me like you're not trying to contribute with information, but are only commenting out of spite. Your last comment, and most of your recent comments would not qualify as constructive to me, so I'd second @GeraldJansen's suggestion to make positive contributions (like [this comment](https://github.com/projecthamster/hamster/pull/630#issuecomment-731761920)), or none at all.



Getting back to the actual subject of this issue: @kidorion, @Pops34, thanks for taking the time to report this issue. I suspect it is the same issue as reported in #590, so I'm going to close this issue as a duplicate of that. We have been aware of that issue for quite a while, but a proper fix turned out a bit more involved that one would hope, and there are a few different approaches, but nothing merged yet. Work on this issue seems to have died down a bit in the last months, for me personally due to other priorities, but I do think this is an important issue to tackle sooner rather than later.

**Closed by matthijskooijman** 2021-02-17 12:11 UTC

**Comment by ederag** [comment] 2021-02-17 12:23
> Your last comment, and most of your recent comments would not qualify as constructive to me

Yet other comments mislead people into *not* testing it.
I deem constructive to give the community another chance to fix the issue.
Sorry you feel otherwise.
