### ISSUE TITLE
Hamster installed from flatpak won't start from Desktop link

### ISSUE THREAD

**Issue by rabin-io** [projecthamster/hamster#713] opened 2023-01-01 08:10 UTC
When starting Hamster from the application menu, I get this error message, 

```
Traceback (most recent call last):
File "/app/lib/python3.10/site-packages/dbus/service.py", line 662, in _message_cb
(candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
File "/app/lib/python3.10/site-packages/dbus/service.py", line 252, in _method_lookup
raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: Activate is not a valid method of interface org.freedesktop.Application 
```

Not sure, but this might be related to issue #692

**Comment by matthijskooijman** [comment] 2023-11-16 20:12
@rabin-io Could you check if activation works when you use the upstream flatpak version instead of the flathub version (if you are not doing this already)? If so, it seems likely that you are indeed seeing #692 and this can be closed as duplicate.

Here's a recent (git master) flatpak build to try (I don't think we have builds of releases yet), scroll down to the bottom: https://github.com/projecthamster/hamster/actions/runs/6891207526

**Comment by rabin-io** [comment] 2023-11-17 14:02
Yep, working.

**Comment by matthijskooijman** [comment] 2023-11-17 16:12
Thanks, then I'm going to close this as a duplicate of #692 for now.

**Closed by matthijskooijman** 2023-11-17 16:12 UTC
