### ISSUE TITLE
Bug: shows "no activity" when theres a still ongoing activity from the past week

### ISSUE THREAD

**Issue by fxkr** [projecthamster/hamster#232] opened 2015-04-19 09:13 UTC
I started work on Sat, 22:10 and forgot to hit stop, so now its Sun, 11:03 (a new week) and the activity is still in progress. I still get "Working on xyz" notifications. However, The Time Tracker window shows "no activity" and I can't click Stop. So I have to the Overview page and back to the previous week to stop the activity.

**Comment by m-antis** [comment] 2017-01-01 19:21
Is this still happening to you @fxkr ?

**Comment by fxkr** [comment] 2017-01-01 20:04
Err, I've stopped using hamster half a year ago (not because I don't like it; I just don't need that kind of time tracking right now). I'd have tested it for you anyway of course, but when I start Hamster now I only get this and never see any activities:

![image](https://cloud.githubusercontent.com/assets/389616/21582727/0579b432-d064-11e6-9ff2-30401934c31e.png)

...so I'm sorry, I can't test it. But if you have a hamster that actually works, it should be easy to test it yourself.

hamster-time-tracker-2.0-0.9.rc1.fc25.noarch on current Fedora 25 (running GNOME v3.22.2 on x11 v1.19.0 (*not* wayland)).

**Comment by ruedigerkupper** [comment] 2018-10-22 19:50
I had this problem with hamster-indicator (stopped working in Ubuntu 18.04). I remember having filed an issue with hamster-indicator. Need to look it up. Perhaps it is the same problem?

**Comment by ruedigerkupper** [comment] 2018-10-22 20:01
Possibly a duplicate of #152.

**Comment by ederag** [comment] 2019-01-13 11:09
Should be fixed by PR #376.
For testing, please consider PR #372 that has been rebased on it, 
and features some other improvements in the UI.
Feedback welcome !

**Closed** 2019-01-17 16:46 UTC
Labels: bug, use_case
