### ISSUE TITLE
Pomodoro timer

### ISSUE THREAD

**Issue by awilkins** [projecthamster/hamster#249] opened 2015-07-28 15:05 UTC
Recently installed pomodoro-indicator from these guys

http://www.atareao.es

Would love it if hamster had this feature.

**Comment by nchachereau** [comment] 2015-08-04 12:06
Hi! Thank you for your interest in Hamster and feature request! This is definitely low priority, given the many problems with the current code base of Hamster and since there are plenty of Pomodoro apps available (see [here](http://www.atareao.es/ubuntu/un-indicador-para-utilizar-la-tecnica-pomodoro-en-ubuntu/) for the post announcing the one referenced by @awilkins).

In any case, I'm marking this as a duplicate of #200. Any further discussion should take place there.

**Closed by nchachereau** 2015-08-04 12:06 UTC
Labels: duplicate
