### ISSUE TITLE
CLI export function gives wrong days as output

### ISSUE THREAD

**Issue by Forage** [projecthamster/hamster#612] opened 2020-05-20 16:16 UTC
Situation:
- 2020-05-17 has no activities
- 2020-05-18 - 2020-05-20 each have multiple activities

Observations:
1. `hamster export xml 2020-05-20` gives me today's activities
2. `hamster export xml 2020-05-17` gives me the activities of 2020-05-18
3. `hamster export xml 2020-05-17 2020-05-17` gives me the activities of 2020-05-18
4. `hamster export xml 2020-05-18` gives me the activities of 2020-05-18 and 2020-05-19
5. `hamster export xml 2020-05-18 2020-05-18` gives me the activities of 2020-05-18 and 2020-05-19
6. `hamster export xml 2020-05-18 2020-05-20` gives me the activities of 2020-05-18 until  2020-05-20

Conclusions:
- Only number 1 and 6 are actually correct.
- 2 and 3 should give me an xml with an empty `activities` element and no `activity` elements
- 4 and 5 should limit the results to only `2020-05-18`

Hamster: 3.0.1

What is the intended behaviour? What can be the cause of the problem?

**Comment by matthijskooijman** [comment] 2020-05-20 16:20
Thanks for reporting! This was actually *just* fixed in 3.0.2, released yesterday. Could you try that and see if it fixes your problem?

If so, this is a duplicate of #576, so I'm closing this already as such. If it turns out 3.0.2 does not fix this for you, we can reopen it again.

**Closed by matthijskooijman** 2020-05-20 16:20 UTC

**Comment by Forage** [comment] 2020-05-20 16:25
Confirmed, 3.0.2 fixes it. Sorry, I missed the new release and the other issue did not show up in my search.
