### ISSUE TITLE
Comma in activity moves to description

### ISSUE THREAD

**Issue by markohrastovec** [projecthamster/hamster#280] opened 2016-01-11 12:51 UTC
Hi,

How can I enter a comma in a title of activity? I am inserting activities via GUI and I always forget that comma stops the activity title and moves everything after comma to a description. That is annoying. Maybe there is a purpose for that in CLI version but in GUI it is confusing.

**Comment by auipga** [comment] 2016-01-16 16:56
same as https://github.com/projecthamster/hamster/issues/270?

**Comment by ederag** [comment] 2019-05-02 20:36
Solving this will require touching very sensitive code, and change behavior. 
It will probably have to wait after v2.3.

**Comment by mwilck** [comment] 2019-10-25 08:36
IMO this is not a bug. The free form text entry field supports some special characters. It's like '`#`' or '`@`' in social media. This is an **important feature** of the text entry field and I'm totally against removing it. I guess the usefulness of the comma as special character can be disputed. @markohrastovec, do you have an alternative suggestion what character should be used to separate activity and description? Put the description in parentheses perhaps? Or trigger only on "`, `" (comma plus whitespace)?

**Comment by ederag** [comment] 2019-10-25 10:26
The plan is to make this a superset of existing functionality.

**Comment by mwilck** [comment] 2019-10-29 08:53
Judging from late discussion on #465, my conviction that this not a bug becomes even stronger.

Being able to type in the full fact (date, start/end time, activity, category, description, and tags) in a _single text field with no need to click back and forth_ between different entry fields is a key feature of hamster. In order to be able to parse the single input line reliably with this large number of fields, we need clear, unequivocal parsing rules. Except for date / time format, there are basically 3 rules: 
 
 1) activity and category are separated by `@`;
  2) description is separated from activity/category by `,`;
  3) tags start with `#`;

Rule 2) could be dropped if we had another way to clearly determine where activity/category ends and the description begins. But we support spaces in activity names, which effectively forbids any classical "tokenization" of the command line. Therefore we do need a separation character, and I see no reason why it shouldn't be `,`.  We can't just replace `,` by another character, because it has been the separator for many years. Making it configurable is also not a good idea, over-configurability just for the sake of a fringe feature like "allowing commas in activity names".

At best, we could relax the rule by only considering `, `  (comma + whitespace) as a separator. This would allow entering activites like `one,two` (without spaces). Yet it would be sort of inconsistent - allowing both whitespace and commas, but not the combination of the two.

Thus my conclusion clearly is - this is not a bug but a wishlist issue that we can't fix without breaking much more important features. And how bad is it, really? Can't you just use `;` or `.` instead?

**Comment by ederag** [comment] 2019-11-01 12:34
That was a wrong automatic close :smile:. To be fully solved it needs #466.

@mwilck I do think we can do better than dismiss this use case,
without losing existing behaviour, to be discussed after v3.0 in #465.

**Comment by mwilck** [comment] 2019-11-04 08:56
> @mwilck I do think we can do better than dismiss this use case

@ederag I'm curious to see your proposal. I'm pretty certain that wrt the comma, we can't do better. Replacing the comma by a different character is not a change towards either better or worse. And some separator will be needed to allow parsing see [comment above](https://github.com/projecthamster/hamster/issues/280#issuecomment-547318607).

**Comment by mwilck** [comment] 2019-11-04 08:57
> Replacing the comma by a different character is not a change towards either better or worse

Correct myself: it would be a change to the worse, because users would have to forget a rule they've been used to for roughly a decade, and learn something else instead.

**Comment by ederag** [comment] 2019-11-04 09:54
@mwilck Not at all:  https://github.com/projecthamster/hamster/issues/280#issuecomment-548772296

**Comment by ederag** [comment] 2019-11-16 17:16
Since there was no more sign of interest, let's take the peaceful road.
That will have to wait until #465, after v3.0.

**Comment by ederag** [comment] 2019-12-14 11:39
The parser had to be overhauled anyway, so this has been fixed in PR #482 as well.

**Closed** 2019-12-27 18:01 UTC
Labels: bug
