### ISSUE TITLE
existing activities starting with the # character are displayed blank and new activities starting with # cannot be added

### ISSUE THREAD

**Issue by pwhipp** [projecthamster/hamster#423] opened 2019-07-17 23:29 UTC
Try adding an activity and typing # as the first character. The Save option is enabled but clicking it has no effect.

If you import a db (or update one for testing) with the # character as the first character in an activity, the activity appears as a blank entry.

**Comment by ederag** [comment] 2019-07-18 05:53
Confirmed, thanks for the report !
Way to reproduce, from the command line:
```bash
> hamster track #123
Error: please specify activity
```

**Comment by mwilck** [comment] 2019-10-25 08:26
IMO this is not a bug. '#' as first character indicates a **tag**. Every person who as ever used or read twitter should be able to grasp that concept. Why is it important to be able to have activities start with '#'?

**Comment by GeraldJansen** [comment] 2019-10-25 08:36
Because #nnn is also often used to refer to an issue or PR in some issue tracking software I suppose.  In the past there has been work on integrating Hamster with Redmine, for example.

**Comment by mwilck** [comment] 2019-10-25 09:05
We can of course discuss exchanging '#' for a different character. We could even make it configurable I guess. But the choice of '#' has always made a lot of sense to me, personally.

Hey, myself I'm working on such issues almost all day. I use '123456@Issues'. I've never felt the need to use '#123456@Issues' instead. Sure, that's a matter of taste. But how long is it that hamster has been using '#' for marking tags? Probably as long as tags have been supported at all.

**Comment by mwilck** [comment] 2019-10-25 09:07
@GeraldJansen, has that Redmine integration work ever lead to anything usable? Is it an active project?

**Comment by GeraldJansen** [comment] 2019-10-25 09:39
@mwilck At least one group has used Redmine integration in the past. The project is inactive, like Hamster itself for lengthy periods ;-) Actually, I don't even know if they used the #nnn in activity names. I was just trying give some possible reasons for this request. I guess it is a "bug" if it worked in the past and no longer works as expected.

**Comment by ederag** [comment] 2019-11-01 12:40
#466 should allow for activities starting with a `#`.
Beware that doing so, you'll be confined to separate fields for this fact.
(losing quickness of the cmdline, cf. #467)
That is tracked in #465 and will be hopefully be solved in a future version.

**Comment by ederag** [comment] 2019-11-16 16:44
Should be fully fixed by the #475 parser change.

**Comment by ederag** [comment] 2019-11-25 14:16
Better fix in #482.

**Closed** 2019-12-27 18:01 UTC
Labels: bug
