### ISSUE TITLE
No longer in Ubuntu 18.04

### ISSUE THREAD

**Issue by ghost** [projecthamster/hamster#356] opened 2018-04-27 15:16 UTC
It's no longer present in Ubuntu 18.04. Installing from the deb doesn't work - running it results in an error. Any plans on making it work for 18.04?

Regards

**Comment by dammer** [comment] 2018-04-27 21:03
@andrei 
I found worкaround for 18.04:
download 2 packages for artful:
[python-wnck_2.32.0+dfsg-4_amd64.deb](http://mirrors.edge.kernel.org/ubuntu/pool/universe/g/gnome-python-desktop/python-wnck_2.32.0+dfsg-4_amd64.deb)
[hamster-applet_2.91.3+git20120514.b9fec3e1-1ubuntu2_all.deb](https://launchpadlibrarian.net/202355025/hamster-applet_2.91.3+git20120514.b9fec3e1-1ubuntu2_all.deb)
and install it throug Gdebi  (python-wnck sould be first)
After install i have error `dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.gnome.Hamster` solution is here https://github.com/projecthamster/hamster/issues/165  now it work for me

**Comment by paulocastroo** [comment] 2018-04-29 23:59
same here, all I get now is:
Traceback (most recent call last):
  File "/usr/bin/hamster", line 30, in <module>
    from hamster import client, reports
ImportError: cannot import name client

But I'm sure there's a workaround for this, finding it currently

**Comment by dammer** [comment] 2018-04-30 09:29
@paulocastroo i newer work with python, only can show [screenshot](https://prnt.sc/jbvvk8) from my system with installation and work hamster-applet.

**Comment by andrei** [comment] 2018-04-30 10:44
Could we have an official package for 18.04 though? I understand that they're working on a new codebase, but still, this could go a long way towards keeping a large dedicated community.

**Comment by joachimjacob** [comment] 2018-04-30 12:47
Hamster is top. But no official package available for Ubuntu 18.04?  This is the only decent time tracking tool in Linux. Thanks for taking this on.

**Comment by andrei** [comment] 2018-05-01 10:14
To be honest I don't know why they are rewriting it, it's a top quality software program and I have found virtually zero bugs while using it. Maybe some other team can take over the legacy code?

**Comment by omarkohl** [comment] 2018-05-02 09:15
As commented by others downloading the packages for Ubuntu 17.10 works. Just leaving some better links:
* https://packages.ubuntu.com/artful/amd64/python-wnck/download
* https://packages.ubuntu.com/artful/all/hamster-applet/download

Then:
```
sudo dpkg -i ~/Downloads/python-wnck_2.32.0+dfsg-4_amd64.deb
sudo dpkg -i ~/Downloads/hamster-applet_2.91.3+git20120514.b9fec3e1-1ubuntu2_all.deb
```
In my case it was NOT necessary to delete `/usr/lib/python2.7/dist-packages/hamster/storage`

**Comment by andrei** [comment] 2018-05-02 10:52
@omarkohl I also had to install python2.7-notify otherwise the time wouldn't update in real time in the main window.

**Comment by elbenfreund** [comment] 2018-05-04 10:11
As you know, this `legacy hamster` package is no longer maintained. And there are no plans for providing packaging for it.

I understand that this is disapointing, but we simply do not have the resources to provide those our self. If some else wants to do so, its FLOSS after all.

@andi5 while it is true that `legacy hamster` is reasonable stable for its users, it's codebase is utterly unmaintainable and a rewrite was the only way to make sure that we can provide our community with a future proof package that meets expectations. As FLOSS developers our resources are limited and a substantial amount of time has been diverted to fixing the `hamster-shell-extension` so it keeps playing nice with `legacy-hamster` while the rewrite is under way.

**Comment by cuu508** [comment] 2018-05-04 12:01
I recently did a clean install of Ubuntu 18.04. After hitting some dead ends, here's how I got legacy hamster running again:

* I downloaded v1.04 source from Github releases
* I installed the dependencies mentioned in README _plus python-gi-cairo_
* I installed it with the "./waf configure" and "./waf install" commands as in README
* at this point I could launch the standalone app and the dbus service was running
* I installed the [gnome-shell extension](https://github.com/projecthamster/hamster-shell-extension) from source, following "Manual Installation For Testing and Development" instructions in its README
* I'm now using it primarily through the shell extension and no issues so far

**Comment by andrei** [comment] 2018-05-04 16:08
@cuu508 It's much easier to install with @omarkohl 's instructions: also see my comments below his.

**Comment by bitinerant** [comment] 2018-05-17 09:56
If you want to do it all on the command line, I think this will get you all of the dependencies, plus https for the downloads.  For me, this provided a working Hamster on a fresh Ubuntu 18.04.

```
cd /tmp
wget https://mirrors.xmission.com/ubuntu/pool/universe/g/gnome-python-desktop/python-wnck_2.32.0+dfsg-4_amd64.deb
wget https://mirrors.xmission.com/ubuntu/pool/universe/h/hamster-applet/hamster-applet_2.91.3+git20120514.b9fec3e1-1ubuntu2_all.deb
sudo apt -y install libwnck22 libwnck-common # dependencies of python-wnck
sudo dpkg -i python-wnck_2.32.0+dfsg-4_amd64.deb
sudo apt -y install python-gconf python-gnome2 libbonoboui2-0 libgnomecanvas2-0 libgnomeui-0 python-pyorbit libglade2-0 libbonoboui2-common libgnomecanvas2-common libgnome-keyring0 libgnomeui-common liborbit2 libgnome-keyring-common libidl-2-0 # dependencies of hamster-applet
sudo dpkg -i hamster-applet_2.91.3+git20120514.b9fec3e1-1ubuntu2_all.deb
sudo apt -y install libcanberra-gtk-module # run-time dependency
```

**Comment by barretr** [comment] 2018-05-17 16:30
Thanks @bitinerant. Same result as before:
`` Traceback (most recent call last):
  File "/usr/bin/hamster-time-tracker", line 591, in <module>
    from hamster.configuration import runtime, dialogs, conf, load_ui_file
ImportError: No module named configuration``

**Comment by julienV** [comment] 2018-05-20 18:54
the solution from @omarkohl worked for me on kubuntu 18.04
i just need to run `sudo apt --fix-broken install` after each dpkg command

**Comment by andyanderso** [comment] 2018-05-22 20:57
For those of us who also like to use hamster-indicator in gnome here are the links to add that back in:
[https://packages.ubuntu.com/artful/all/hamster-indicator/download](url)

Install with ->
`sudo dpkg -i ~/Downloads/hamster-indicator_0.1+037dd2e-0ubuntu2_all.deb`

**Comment by andyanderso** [comment] 2018-06-08 13:46
Thanks, @sereno. The link should work now.

**Comment by tanius** [comment] 2018-09-04 15:09
Putting the instructions [by @bitinerant](#issuecomment-389812775) and [by @andyanderso](#issuecomment-391138302) together and combining it with [this technique](https://unix.stackexchange.com/a/159114) here's a nice way to install everything (hamster-applet and hamster-indicator) under Ubuntu 18.04:

    wget https://mirrors.xmission.com/ubuntu/pool/universe/g/gnome-python-desktop/python-wnck_2.32.0+dfsg-4_amd64.deb
    wget https://mirrors.xmission.com/ubuntu/pool/universe/h/hamster-applet/hamster-applet_2.91.3+git20120514.b9fec3e1-1ubuntu2_all.deb
    wget https://mirrors.xmission.com/ubuntu/pool/universe/h/hamster-indicator/hamster-indicator_0.1+037dd2e-0ubuntu2_all.deb

    sudo apt install \
      ./python-wnck_2.32.0+dfsg-4_amd64.deb \
      ./hamster-applet_2.91.3+git20120514.b9fec3e1-1ubuntu2_all.deb \
      ./hamster-indicator_0.1+037dd2e-0ubuntu2_all.deb \
      libcanberra-gtk-module

**Comment by mrestom** [comment] 2018-09-18 05:51
Thank you very much @tanius !

**Comment by MTindev** [comment] 2018-09-20 10:12
Hello,

For me, on a fresh 18.04, after the installation according to the README, when typing `$ hamster` the error was : 
```
/usr/lib/python2.7/dist-packages/hamster/lib/configuration.py:33: PyGIWarning: GConf was imported without specifying a version first. Use gi.require_version('GConf', '2.0') before import to ensure that the right version gets loaded.
[...]
ImportError: No module named cairo
```

So, I installed two other packages, because "cairo" was missing : 
```
$ sudo apt-get install python-cairo
$ sudo apt-get install python-gi-cairo
```

I redo the building and that works fine.

N.B.  For the gnome-shell-extension, I installed it from the source (according to its README), because the available one in extensions.gnome.org was in error).

As seen in #357 and #269, theses packages may be added to the README ?

**Comment by zyphlar** [comment] 2018-09-25 21:11
@tanius this technique worked for me but I also had to install libcanberra-gtk0 beforehand for libcanberra-gtk-module to work.

**Comment by nleo** [comment] 2018-09-29 06:17
@tanius  not woks

```
WARNING:root:Could not import gnomeapplet. Defaulting to upper panel
Traceback (most recent call last):
  File "/usr/bin/hamster-indicator", line 385, in <module>
    hamster_indicator = HamsterIndicator()
  File "/usr/bin/hamster-indicator", line 175, in __init__
    super(HamsterIndicator, self).__init__(applet)
  File "/usr/lib/python2.7/dist-packages/hamster/applet.py", line 205, in __init__
    self.new_name = widgets.ActivityEntry()
  File "/usr/lib/python2.7/dist-packages/hamster/widgets/activityentry.py", line 103, in __init__
    self.populate_suggestions()
  File "/usr/lib/python2.7/dist-packages/hamster/widgets/activityentry.py", line 234, in populate_suggestions
    self.activities = runtime.storage.get_activities(fact.activity)
  File "/usr/lib/python2.7/dist-packages/hamster/client.py", line 136, in get_activities
    return self._to_dict(('name', 'category'), self.conn.GetActivities(search))
  File "/usr/lib/python2.7/dist-packages/hamster/client.py", line 87, in conn
    '/org/gnome/Hamster'),
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.gnome.Hamster exited with status 1
```

**Comment by ruedigerkupper** [comment] 2018-10-21 10:58
I have the same problem as nleo reports. Any help?

**Comment by NikMel** [comment] 2018-10-25 15:54
I have the same problem, now on Ubuntu 18.10. Starting 'hamster' results in:
Traceback (most recent call last):
  File "/usr/bin/hamster", line 30, in <module>
    from hamster import client, reports
ImportError: cannot import name client

Similar problems when trying to run the dbus services:
 - /usr/lib/hamster-time-tracker/hamster-service
Traceback (most recent call last):
  File "/usr/lib/hamster-time-tracker/hamster-service", line 19, in <module>
    from hamster.lib import i18n
ImportError: cannot import name i18n

- /usr/lib/hamster-time-tracker/hamster-windows-service 
Traceback (most recent call last):
  File "/usr/lib/hamster-time-tracker/hamster-windows-service", line 54, in <module>
    from hamster.lib import i18n
ImportError: cannot import name i18n

I've built from git master (commit c3e5fb761c88fd):
1.  ./waf configure build --prefix=/usr
2. sudo ./waf install

I've also gone through most of this thread and tried:
- Deleted /usr/lib/python2.7/dist-packages/hamster
- Tried to install hamster 2.91 from the deb linked above

But to no avail, I get the exact same error.

I really miss hamster... And, in about 10 days I'm supposed to report my working hours for October :/

I'm at my wits end here and would be happy to try pretty much anything, so please suggest something....

All the best,
Niklas

**Comment by NikMel** [comment] 2018-10-25 16:42
Adding a little more... Not quite sure what I'm looking for, so it might just be random stuff.

> python --version
Python 2.7.15+

Issuing help("modules") in python indeed shows hamster present, so the module is installed and available!
importing the hamster module works, and dir(hamster) shows:
['__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__']

But printing hamster.__file__ shows its installed in .local/lib/python2.7/site-packages, and not /usr/lib/[...]

Can't see "client" anywhere in there... 

Also hamster.lib seems to be present, but I can't find i18n anywhere in that either. 

/niklas

**Comment by andrei** [comment] 2018-10-25 17:03
@NikMel Maybe downgrade to 18.04 (LTS). All users managed to set it up on that. Maybe your issue comes from 18.10

**Comment by NikMel** [comment] 2018-10-25 17:10
> @NikMel Maybe downgrade to 18.04 (LTS). All users managed to set it up on that. Maybe your issue comes from 18.10

Yup, but since I just went through the trouble of making a clean 18.10 install, I was ofcourse hoping to find a solution to this...

**Comment by abraxxa** [comment] 2018-10-25 18:02
I‘ve installed the deb files from 17.10 and hamster works even after upgrading from 18.04 to 18.10.
I guess you habe installed some hamster libs in your local python environment additionally to the system modules.

**Comment by NikMel** [comment] 2018-10-25 18:39
> I‘ve installed the deb files from 17.10 and hamster works even after upgrading from 18.04 to 18.10.
> I guess you habe installed some hamster libs in your local python environment additionally to the system modules.

Great help, thanks! For any future references, I made the effort to clean out all remnants of hamster from my system:
- sudo updatedb
- locate hamster
And made sure there wasn't anything left (found stuff in /usr/lib /usr/local/lib and ~/.local/lib) 

Then installed the deb from an earlier post (2.91-something).

And now it works! The problem was junk left from attempts to build from git.

Very happy,
/Niklas

**Comment by sr258** [comment] 2018-10-31 17:06
Would packing Hamster and all dependencies into a snap resolve these issues for future OS updates?

**Comment by edgardoadriano** [comment] 2018-11-01 23:42
> sudo apt install \ ./python-wnck_2.32.0+dfsg-4_amd64.deb \ ./hamster-applet_2.91.3+git20120514.b9fec3e1-1ubuntu2_all.deb \ ./hamster-indicator_0.1+037dd2e-0ubuntu2_all.deb \ libcanberra-gtk-module

worked like a charm in Mint 19 - Mate , muchas gracias!!!!! :)

**Comment by diosney** [comment] 2018-11-29 15:16
@tanius Works like a charm on Kubuntu 18.04 too. Thanks.

**Comment by matthijskooijman** [comment] 2019-03-16 16:06
I guess this issue is about getting the old (pre-rewrite) hamster-applet packaging working again. Summarizing: from https://github.com/projecthamster/hamster/issues/356#issuecomment-386558355 I understand that there are no plans to update the existing packages to work on newer systems (since that would require significant changes) . However, at https://github.com/projecthamster/hamster/issues/356#issuecomment-418404342 a workaround is described (installing older package versions) to get legacy hamster working.

I wanted to add that #252 is about getting the newer, rewritten version packaged for Debian & Ubuntu (so let's keep these discussions separate).

**Comment by ederag** [comment] 2019-03-16 18:40
Here is a summary of current status and goals:
1) There are no plans to update the old, stable, "hamster-applet" (<= version 1.04)
  because it is too difficult to migrate on new platforms that dropped pygtk.
2) The short term goal is to have a usable version fully compatible with the legacy database,
  hopefully stable, that works on new platforms.
This is based on the gtk3 port, and active development is pursued on this repository master (current release is [v2.2.2](https://github.com/projecthamster/hamster/releases/tag/v2.2.2)). It seems to work fine on ubuntu-18.10.
There may be new bugs so be careful to backup your `hamster.db`, but I'm striving to merge only working snapshots into master (early feedback would be precious, so please test PRs and comment).
The idea is to give time for the "*rewrite*" to proceed peacefully.
3) The long term goal: the *rewrite*, done in `hamster-*` repos ([hamster-lib](https://github.com/projecthamster/hamster-lib), [hamster-gtk](https://github.com/projecthamster/hamster-gtk), ...).

**Comment by matthijskooijman** [comment] 2019-03-16 19:22
@ederag, thanks for confirming. Seems I was thinking 2. and 3. were the same thing and both were in this repo, but now I see this is not the case. In that case, I think this issue and #252 might be essentially the same, but perhaps it's good to keep this issue around for the workaround to get 1. working, and keep #252 for any work on getting 2. back in Debian & Ubuntu.

**Comment by GeraldJansen** [comment] 2019-03-31 18:08
From the command line I kept getting this warning:
`(hamster:23263): dbind-WARNING **: 19:58:18.111: Couldn't register with accessibility bus: Blah, blah...`
Putting this in /etc/environment or ~/.profile silences this warning:
`export NO_AT_BRIDGE=1`
(from https://wiki.archlinux.de/title/GNOME#Tipps_und_Tricks)

**Comment by Sea-Wing-designs** [comment] 2019-04-18 04:13
Is there a way to at least read the hamster.db file so I can get the last two weeks of billable client hours off of it?  I tried to install the and I can get the overview window to open but the other windows won't.  If I could somehow get that overview window to display my old DB I would be very happy.

**Comment by GeraldJansen** [comment] 2019-04-18 06:02
@Sea-Wing-designs Try these from the command line (`hamster --help`):
`hamster list 2019-04-01 2019-04-14`
`hamster export tsv 2019-04-01 2019-04-14`

**Comment by cuu508** [comment] 2019-04-18 06:07
@Sea-Wing-designs if it's just to get data off hamster.db n a hurry, you could install an older Ubuntu release in a VM, install Hamster from repositories, and drop in the hamster.db file. Obviously this would not be a day-to-day solution, but just to get the invoices done.

**Comment by GeraldJansen** [comment] 2019-04-18 06:22
@Sea-Wing-designs You may just need to copy hamster.db from ~/.local/share/hamster-applet to ~/.local/share/hamster-time-tracker (or maybe the reverse - take care to backup first!).

**Comment by abraxxa** [comment] 2019-04-18 06:26
You could also use the SQLite database browser, it‘s in the Ubuntu package repository.

**Comment by Sea-Wing-designs** [comment] 2019-04-18 14:53
@GeraldJansen, thanks for the reply,
.local/share/hamster-time-tracker doesn't exist

@abraxxa, thanks for the tip in SQLite.  That kind of helps, it will take time sorting it all out, but better than nothing.

@cuu508, You reminded me that I have an old laptop that I might still be able to turn on that has not been updated.

**Comment by NikMel** [comment] 2019-04-18 15:03
@Sea-Wing-designs  hamster.db might also be in .local/share/hamster-applet/ 
In Sqlite, use the query:
`select * from activities inner join facts on activity_id=activities.id;`
to get activities with start and end time. Export it to a textfile and import into LibreOffice Calc separating fields on | and you should have something fairly workable.

**Comment by Sea-Wing-designs** [comment] 2019-04-18 15:40
The old laptop did the trick.

**Comment by Sea-Wing-designs** [comment] 2019-04-18 15:43
@NikMel, thank you for that tip.  I may use that in the future if I need to get data from that file.  

I hope that Hamster is resurrected.  It was really very helpful for my business.

**Comment by GeraldJansen** [comment] 2019-04-18 16:15
I have used v1.04 for years for my business needs. I have recently installed v2.x (with some hiccups) and find it quite usable for data collection. (I do my own reports, now using tsv data exports). I'd like to cheer on @ederag and other contributors for keeping hamster alive. For me the key priority is getting rid of the the python2 dependency for installation considering the fast approaching end-of-life for python2.7 (2020-01-01).

**Comment by Sea-Wing-designs** [comment] 2019-05-15 21:17
I would like to get hamster running on kubuntu 18.0.  I have downloaded the package and installed the listed dependencies.  I am a little lost on how to actually install the package.  Could someone please point me to clear instructions to build and install Hamster.  I don't follow how to "Adapt to my system" or if that is needed, and I get this:  ./waf: command not found.  Any help would be greatly appreciated.

**Comment by diosney** [comment] 2019-05-15 23:32
@Sea-Wing-designs I was able to run it perfectly in Kubuntu 18.04 64bits just do:

wget https://mirrors.xmission.com/ubuntu/pool/universe/g/gnome-python-desktop/python-wnck_2.32.0+dfsg-4_amd64.deb
wget https://mirrors.xmission.com/ubuntu/pool/universe/h/hamster-applet/hamster-applet_2.91.3+git20120514.b9fec3e1-1ubuntu2_all.deb
wget https://mirrors.xmission.com/ubuntu/pool/universe/h/hamster-indicator/hamster-indicator_0.1+037dd2e-0ubuntu2_all.deb

sudo apt install \
  ./python-wnck_2.32.0+dfsg-4_amd64.deb \
  ./hamster-applet_2.91.3+git20120514.b9fec3e1-1ubuntu2_all.deb \
  ./hamster-indicator_0.1+037dd2e-0ubuntu2_all.deb \
  libcanberra-gtk-module

**Comment by Sea-Wing-designs** [comment] 2019-05-16 15:28
Thank you @diosney.  The first one,  wget https://mirrors.xmission.com/ubuntu/pool/universe/g/gnome-python-desktop/python-wnck_2.32.0+dfsg-4_amd64.deb, comes back with this:  
HTTP request sent, awaiting response... 404 Not Found
2019-05-16 08:20:05 ERROR 404: Not Found.

I tried without that and the applet will start to load and then stops.

**Comment by diosney** [comment] 2019-05-16 16:50
@Sea-Wing-designs It seems that all packages are required, try download the missing one from other place, for example:

https://mirrors.xmission.com/ubuntu/pool/universe/g/gnome-python-desktop/python-wnck_2.32.0%2Bdfsg-3_amd64.deb
http://security.ubuntu.com/ubuntu/pool/universe/g/gnome-python-desktop/python-wnck_2.32.0+dfsg-3_amd64.deb

I did that procedure a while ago, maybe in the meantime it was removed.

**Comment by Sea-Wing-designs** [comment] 2019-05-16 17:31
I tried those with wget and they seemed to work. But I am still in the place I was before, I can get the Hamster Overview to load, but not the indicator or the time tracker.

**Comment by Sea-Wing-designs** [comment] 2019-05-16 20:05
I tried removing it entirely and going through the steps again and it is still doing the same thing.  It starts to load and then stops after about 2 seconds.

**Comment by diosney** [comment] 2019-05-16 20:39
@Sea-Wing-designs I've no idea what would be happening to you, with all those steps I was able to make it into working properly.

Did you tried a full update and upgrade after that?

**Comment by Sea-Wing-designs** [comment] 2019-05-17 02:33
@diosney I did update and upgrade.  I hope that I can get it working somehow.

**Comment by GeraldJansen** [comment] 2019-05-17 21:12
@Sea-Wing-designs If you want to try a more recent v2.x version of Hamster from source, as it appeared from your first message, you can check out [these instructions](https://github.com/GeraldJansen/hamster/wiki/Hamster-2.x-on-Xubuntu-18.04) for Xubuntu 18.04. I just finished checking them on a fresh install. Kubuntu should be similar, although it is possible that some needed gnome packages are automatically installed on Xubuntu but not on Kubuntu. Make sure to uninstall (sudo apt-get purge) the old hamster-applet/indicator packages first!

**Comment by Sea-Wing-designs** [comment] 2019-05-18 02:19
Thank you, I will try that @GeraldJansen

**Comment by Sea-Wing-designs** [comment] 2019-05-19 18:58
@GeraldJansen, those instructions worked, I think.  The interface has changed a lot and I don't know if I am missing something or it is just the way it is now, but I don't see a window that has start and stop time.  A cool thing is that it somehow grabbed all of my previous categories and tags.

**Comment by GeraldJansen** [comment] 2019-05-19 19:30
@Sea-Wing-designs Yes, the v2.x interface based on Gtk3 lost a lot of niceness of the old hamster-applet, but on the other hand it is gaining some new niceness like the keyboard shortcuts (#387) :-)  It probably picked up your old hamster.db as the DB backend is unchanged from hamster-applet.

**Comment by holderl5** [comment] 2019-06-10 01:33
All,

I haven't tried this in 19.04, I made a docker container instead:
https://github.com/holderl5/docker-hamster

**Comment by pwhipp** [comment] 2019-07-09 20:41
For anyone else here with a clean install: @GeraldJansen has provided [good instructions](https://github.com/GeraldJansen/hamster/wiki/Hamster-2.x-on-Xubuntu-18.04) but when you do the configure step make sure that everything is found. You may also need glib-genmarshal, libglib2.0-dev, libdbus-glib-1-dev, docbook-utils, gnome-doc-utils, xsltproc.

If importing existing data, copy ./local/share/hamster-applet/hamster.db from your old to your new system (as @GeraldJansen says, it appears to be compatible but note ).

When updating stuff like the start time etc. you may have to restart the app.

**Comment by GeraldJansen** [comment] 2019-07-10 05:46
Thanks @pwhipp. I've moved the instructions to the main Hamster wiki ([here](https://github.com/projecthamster/hamster/wiki/Hamster-2.x-on-Xubuntu-18.04)) and added a link to your note.

**Comment by ederag** [comment] 2019-07-10 12:12
@pwhipp 

> If importing existing data, copy ./local/share/hamster-applet/hamster.db from your old to your new system (as @GeraldJansen says, it appears to be compatible but [note this issue](https://github.com/projecthamster/hamster/issues/270)).

Please file an issue, using an old database should work flawlessly.

> When updating stuff like the start time etc. you may have to restart the app.

That might have been fixed in current master. Otherwise please file an issue.

**Comment by pwhipp** [comment] 2019-07-15 23:38
@ederag
The problem with existing dbs is that they may contain entries with a hash or number as the first element of the activity. These appear blank in the current version of hamster. In my case I have a lot of activities relating to tracking systems and use "#nnn some explanation" to relate the activity to the issue in the tracking system (#nnn might be a JIRA issue number for example). To make my db compatible, I did an update on the activity table changing all the # characters at the start of the activity into 'ADM-' (and the search text to 'adm-'). That allowed my old db to work fine with the new code.

I'm not sure this warrants an issue of its own because I think it's covered by active work in progress but I can add it if you think its worthwhile.

**Comment by ederag** [comment] 2019-07-16 06:29
@pwhipp Yes, please file an issue, because it is a relevant use case, not yet fixed,
and any old database should work out of the box.

**Comment by pwhipp** [comment] 2019-07-17 23:31
@ederag Done - #423

**Comment by ederag** [comment] 2019-07-30 19:44
After the waf update (#421), the installation works smoothly again in ubuntu-18.04.
(tested in a fresh virtualbox)

**Comment by ederag** [comment] 2019-08-27 16:18
There was a [report]( https://github.com/projecthamster/hamster/issues/402#issuecomment-525297678) of successful installation in 18.04, after removal of all previous hamster files, 
especially in `/usr/local`.

**Comment by cuu508** [comment] 2019-08-28 06:35
I recently installed a fresh Ubuntu 19.04, and (to my surprise) managed to get the old Hamster 1.04 running. I basically grabbed the tarball, ran the waf commands as instructed in README and installed missing dependencies until it started up.

I then tried a few different Gnome Shell extensions from extensions.gnome.org until I found one that worked. I think it was this one: https://extensions.gnome.org/extension/1834/hamster-time-tracker/

**Comment by GeraldJansen** [comment] 2019-08-28 07:46
I can confirm that the same extension version works fine together with the current master branch of hamster (installed manually on Ubuntu 19.04 following the current README).

**Comment by ederag** [comment] 2019-09-01 18:06
So hamster can easily be installed on ubuntu, thanks for the confirmations !
Packaging is discussed on #252.

**Closed by ederag** 2019-09-01 18:06 UTC

**Comment by ederag** [comment] 2020-01-30 20:24
It should be possible to release v3.0 by the end of next week, but
*Kind word of warning, posted here because #252 has no hits  these weeks*;
No-one answered a [request about deadlines](https://github.com/projecthamster/hamster/issues/252#issuecomment-577819669) since last week.
Please understand that I know that packaging is tough work (did some for openSUSE),
someone else has to chime in or there will be no hamster 3.0 package in ubuntu 20.04 (LTS version).

**Comment by ederag** [comment] 2020-02-20 04:20
Kind heads up: if everyone thinks "someone else will do it eventually", 
the LTS deadline [feb 27th](https://wiki.ubuntu.com/FocalFossa/ReleaseSchedule) will be missed.
The clean debian route is already [cut](https://github.com/projecthamster/hamster/issues/252#issuecomment-587847269).
#569 should help (if that was a concern to anyone), thanks to @matthijskooijman, 
v3.0 will be released this week-end, so it's frozen now,
but please ask away questions about the installation process if need be.
